<a href="https://colab.research.google.com/github/NikhilRana2076/PythonAssignment/blob/main/Assignment_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) Find the inverse of the following matrices.

A= [1 2 3

55 66 7]

B= [1 2 3

55 66 77

6 7 12]


C= [1 2 3 8 

5 6 7  5

6 7 12 12

11 12 13 20]

In [57]:
import numpy as np
  
A = np.array([[1, 2, 3], [55, 66, 7]])
print(A)
try:
  A_inv = np.linalg.inv(A)
except:
  print("For inverse the martix should be square.\n")
  
B = np.array([[1, 2, 3], 
                [55, 66, 7], 
                [6, 7, 12]])
  
inverse_array = np.linalg.inv(B)
print("Inverse array is ")
print(inverse_array)
print()
  
C = np.array([[1, 2, 3, 8], 
                [5, 6, 7, 5],
                [6, 7, 12, 12], 
                [11, 12, 13, 20]])
  
inverse_array = np.linalg.inv(C)
print("Inverse array is ")
print(inverse_array)
print()
  

[[ 1  2  3]
 [55 66  7]]
For inverse the martix should be square.

Inverse array is 
[[-1.41254753  0.00570342  0.34980989]
 [ 1.17490494  0.01140684 -0.30038023]
 [ 0.02091255 -0.0095057   0.08365019]]

Inverse array is 
[[-0.85576923 -0.78205128  0.25        0.38782051]
 [ 0.75        1.         -0.5        -0.25      ]
 [-0.08653846 -0.06410256  0.25       -0.09935897]
 [ 0.07692308 -0.12820513 -0.          0.05128205]]



2) Find the values of x1, x2 and x3.

5x1 + 4 x2 + 3 x3 = 5

6x1 - 8x2   + 7x3 = 15

x1   - x2     +10x3 = 25   


In [ ]:
import numpy as np
arr = np.array([[5, 4, 3], 
                [6, -8, 7], 
                [1, -1, 10]])
  
inverse_array = np.linalg.inv(arr)
print("Inverse array is ")
print(inverse_array)
print()

print("\n The values of x1, x2, x3 are: ")
A= inverse_array
B = [[5],[15], [25]]
    
result= [[0],[0],[0]]
  
result = np.dot(A,B)
 
for r in result:
    print(r)

Inverse array is 
[[ 0.12784588  0.07530648 -0.0910683 ]
 [ 0.09281961 -0.08231173  0.02977233]
 [-0.00350263 -0.01576182  0.11208406]]


 The values of x1, x2, x3 are: 
[-0.50788091]
[-0.0262697]
[2.54816112]


3) Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.


In [ ]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


4) Write a NumPy program to compute the eigenvalues and eigenvectors of a given square array.
B= [1 2 3 

55 66 7

6 7 12]

In [ ]:
import numpy as np
m = np.mat([[1, 2, 3], 
                [55, 66, 7], 
                [6, 7, 12]])
print("Original matrix:")
print("a\n", m)
w, v = np.linalg.eig(m) 
print( "Eigenvalues of the said matrix\n",w)
print( "Eigenvectors of the said matrix\n",v)

Original matrix:
a
 [[ 1  2  3]
 [55 66  7]
 [ 6  7 12]]
Eigenvalues of the said matrix
 [68.81905127 -0.70229368 10.88324241]
Eigenvectors of the said matrix
 [[ 0.03480353  0.77221412  0.21267997]
 [ 0.99144253 -0.6351919  -0.32907749]
 [ 0.12581905 -0.01471714  0.92004089]]


5) Write a NumPy program to generate five random numbers from the normal distribution.



In [ ]:
import numpy as np
x = np.random.normal(size=5)
print(x)

[-2.07178985 -0.5965234   1.39320665  1.17318249 -1.81762955]


6) Write a NumPy program to generate six random integers between 10 and 30.


In [ ]:
import numpy as np
x = np.random.randint(low=10, high=30, size=6)
print(x)

[15 22 10 25 18 17]


7) Write a NumPy program to create a 3x3x3 array with random values.


In [ ]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.98673068 0.3353269  0.17554909]
  [0.83252441 0.96207668 0.68561838]
  [0.84624178 0.81665328 0.30847146]]

 [[0.87253405 0.73311285 0.85076937]
  [0.83564758 0.7514812  0.54069952]
  [0.91765965 0.27544515 0.55003476]]

 [[0.63878755 0.97192004 0.04247284]
  [0.19878941 0.72136041 0.7088099 ]
  [0.14664395 0.94056774 0.00547557]]]


8) Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.


In [ ]:
import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("\nThe minimum value is", xmin)
print("The maximum value is", xmax)



Original Array:
[[0.34822957 0.62372785 0.92214217 0.07811551 0.25606508]
 [0.98986797 0.53179231 0.01720714 0.94275862 0.18750238]
 [0.87136037 0.11886019 0.24499648 0.66494109 0.87771564]
 [0.06755365 0.63087482 0.25335802 0.89472839 0.16643079]
 [0.21063269 0.30801074 0.28304016 0.93815949 0.40582071]]

The minimum value is 0.017207143305550288
The maximum value is 0.9898679712175589


9) Write a NumPy program to normalize a 3x3 random matrix.


In [5]:
import numpy as np
x= np.random.random((3,3))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("\nAfter normalization:")
print(x)

Original Array:
[[0.89086553 0.73487058 0.24082275]
 [0.18852878 0.71651028 0.96862019]
 [0.45594411 0.37475949 0.97960358]]

After normalization:
[[0.88782597 0.69063228 0.06610497]
 [0.         0.66742298 0.98611587]
 [0.33804051 0.23541479 1.        ]]


10) Write a NumPy program to create a random vector of size 10 and sort it.


In [6]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x.sort()
print("\nSorted array:")
print(x)

Original array:
[0.00458559 0.90753882 0.32421787 0.66005943 0.21335033 0.96329255
 0.77433812 0.25348729 0.58743261 0.84974284]

Sorted array:
[0.00458559 0.21335033 0.25348729 0.32421787 0.58743261 0.66005943
 0.77433812 0.84974284 0.90753882 0.96329255]


11) Write a NumPy program to check if two random arrays are equal or not.


In [7]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("\nTest above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 1 1 0 1 0]
Second array:
[0 0 0 1 1 1]

Test above two arrays are equal or not!
False


12) Write a NumPy program to create a random vector of size 15 and replace the maximum value by -1.


In [9]:
import numpy as np
x = np.random.random(15)
print("Original array:")
print(x)
x[x.argmax()] = -1
print("\nMaximum value replaced by -1:")
print(x)


Original array:
[0.64704811 0.05584391 0.36409024 0.53970666 0.70179511 0.82400611
 0.83534335 0.35433891 0.426412   0.84986262 0.25638872 0.33814446
 0.12347345 0.95208346 0.83003698]

Maximum value replaced by -1:
[ 0.64704811  0.05584391  0.36409024  0.53970666  0.70179511  0.82400611
  0.83534335  0.35433891  0.426412    0.84986262  0.25638872  0.33814446
  0.12347345 -1.          0.83003698]


13) Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on a flattened array.

A= [1 2

11 12]

In [12]:
import numpy as np
a = np.array([[1,2],[11,12]])
print("Original array:")
print(a)
print("\nSort the array along the first axis:")
print(np.sort(a, axis=0))
print("\nSort the array along the last axis:")
print(np.sort(a))
print("\nSort the flattened array:")
print(np.sort(a, axis=None))

Original array:
[[ 1  2]
 [11 12]]

Sort the array along the first axis:
[[ 1  2]
 [11 12]]

Sort the array along the last axis:
[[ 1  2]
 [11 12]]

Sort the flattened array:
[ 1  2 11 12]


14) Write a NumPy program to sort the student id with increasing height of the students from given students id and height. Print the integer indices that describe the sort order by multiple columns and the sorted data.

id       height

123 145

126 155

140 165

152 153

In [17]:
import numpy as np
student_id = np.array([123, 126, 140, 152])
student_height = np.array([145, 155, 165, 153])
#Sort by studen_id then by student_height
indices = np.lexsort((student_id, student_height))
print("Sorted indices:")
print(indices)
print("\nSorted data:")
for n in indices:
  print(student_id[n], student_height[n])

Sorted indices:
[0 3 1 2]

Sorted data:
123 145
152 153
126 155
140 165


15) Write a NumPy program to get the indices of the sorted elements of a given array.

X = [1023 5202 6230 1671 1682 5241 4532]


In [18]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
print("Original array:")
print(student_id)
i = np.argsort(student_id)
print("\nIndices of the sorted elements of a given array:")
print(i)

Original array:
[1023 5202 6230 1671 1682 5241 4532]

Indices of the sorted elements of a given array:
[0 3 4 6 1 5 2]


16) Write a NumPy program to sort a given complex array using the real part first, then the imaginary part.

Y = [(1+2j), (3-1j), (3-2j), (4-3j), (3+5j)]

In [15]:
import numpy as np
complex_num = [1 + 2j, 3 - 1j, 3 - 2j, 4 - 3j, 3 + 5j]
print("Original array:")
print(complex_num)
print("\nSorted a given complex array using the real part first, then the imaginary part.")
print(np.sort_complex(complex_num))

Original array:
[(1+2j), (3-1j), (3-2j), (4-3j), (3+5j)]

Sorted a given complex array using the real part first, then the imaginary part.
[1.+2.j 3.-2.j 3.-1.j 3.+5.j 4.-3.j]


17) Multiply AXB

A= [1 2 

11 12

12 15]

B= [1 2 3

11 12 13]


In [21]:
import numpy as np

A = np.mat([[1, 2], 
                [11, 12], 
                [12, 15]])
B = np.mat([[1, 2, 3], 
                [11, 12, 13]])
    
multi= ([[0, 0, 0], 
                [0, 0, 0], 
                [0, 0, 0]])
  
multi = np.dot(A,B)
 
for r in multi:
    print(r)

[[23 26 29]]
[[143 166 189]]
[[177 204 231]]


18) Write a NumPy program to compute ex, element-wise of a given array.

A = [1,5,6,9]


In [22]:
import numpy as np
x = np.array([1, 5, 6, 9], np.float32)
print("Original array: ")
print(x)
print("\ne^x, element-wise of the said:")
r = np.exp(x)
print(r)

Original array: 
[1. 5. 6. 9.]

e^x, element-wise of the said:
[2.7182820e+00 1.4841316e+02 4.0342877e+02 8.1030840e+03]


19) Write a NumPy program to compute natural, base 10, and base 2 logarithms for all elements in a given array.

A = [1,2.5,56,19]


In [23]:
import numpy as np
x = np.array([1, 2.5, 56, 19])
print("Original array: ")
print(x)
print("\nNatural log =", np.log(x))
print("Common log =", np.log10(x))
print("Base 2 log =", np.log2(x))

Original array: 
[ 1.   2.5 56.  19. ]

Natural log = [0.         0.91629073 4.02535169 2.94443898]
Common log = [0.         0.39794001 1.74818803 1.2787536 ]
Base 2 log = [0.         1.32192809 5.80735492 4.24792751]


20) Write a NumPy program to calculate the difference between the maximum and the minimum values of a given array along the second axis.

A = [[ 0 1 2 3 4 5]

[ 6 7 8 9 10 11]]


In [33]:
import numpy as np
A = np.array([[ 0, 1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10, 11]])
r1 = np.ptp(A, 1)
r2 = np.amax(A, 1) - np.amin(A, 1)
assert np.allclose(r1, r2)
print("Diff. between max and min values of the said array:")
print(r1)

Diff. between max and min values of the said array:
[5 5]


21) Write a NumPy program to compute the median of a flattened given array.

B =[[ 0 1 2 3 4 5]

[ 6 7 8 9 10 11]]

In [35]:
import numpy as np
B = np.array([[ 0, 1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10, 11]])
r1 =  np.median(B)
print("Median of said array:")
print(r1)

Median of said array:
5.5


22) Write a NumPy program to compute cross-correlation of two given arrays.

A= [0 1 3]

B = [2 4 5]

In [39]:
import numpy as np
A = np.array([0, 1, 3])
B = np.array([2, 4, 5])
print("Original array A:")
print(A)
print("\nOriginal array B:")
print(B)
print("\nCross-correlation of the arrays:\n",np.cov(A, B))

Original array A:
[0 1 3]

Original array B:
[2 4 5]

Cross-correlation of the arrays:
 [[2.33333333 2.16666667]
 [2.16666667 2.33333333]]


23)  Write a Python program to count the number of occurrences of each value in a given array of non-negative integers.

A = [0, 1, 6, 1, 4, 1, 2, 2, 7]



In [42]:
import numpy as np
array = [0, 1, 6, 1, 4, 1, 2, 2, 7] 
print("Original array:")
print(array)
print("\nNumber of occurrences of each value in array: ")
print(np.bincount(array))

Original array:
[0, 1, 6, 1, 4, 1, 2, 2, 7]

Number of occurrences of each value in array: 
[1 3 2 0 1 0 1 1]


24) Write a NumPy program to display all the dates for the month of May, 2021.



In [44]:
import numpy as np
print("May, 2021")
print(np.arange('2021-05', '2021-06', dtype='datetime64[D]'))

May, 2021
['2021-05-01' '2021-05-02' '2021-05-03' '2021-05-04' '2021-05-05'
 '2021-05-06' '2021-05-07' '2021-05-08' '2021-05-09' '2021-05-10'
 '2021-05-11' '2021-05-12' '2021-05-13' '2021-05-14' '2021-05-15'
 '2021-05-16' '2021-05-17' '2021-05-18' '2021-05-19' '2021-05-20'
 '2021-05-21' '2021-05-22' '2021-05-23' '2021-05-24' '2021-05-25'
 '2021-05-26' '2021-05-27' '2021-05-28' '2021-05-29' '2021-05-30'
 '2021-05-31']


25) Write a NumPy program to concatenate element-wise two arrays of string.

A = ['Python' 'PHP']

B = [' Java' ' C++']



In [49]:
import numpy as np
x1 = np.array(['Python', 'PHP'], dtype=np.str)
x2 = np.array([' Java', ' C++'], dtype=np.str)
print("Array1:")
print(x1)
print("Array2:")
print(x2)
new_array = np.char.add(x1, x2)
print("\nNew array:")
print(new_array)

Array1:
['Python' 'PHP']
Array2:
[' Java' ' C++']

New array:
['Python Java' 'PHP C++']
